### ISSUE TITLE
Not compatible with latest wetterdienst Version

### ISSUE THREAD

**Issue by deepweather** [earthobservations/wetterdienst-ui#1]
Due to renaming of many classes and input parameters in the latest Version of wetterdienst package, the UI App does not work with the current wetterdienst release. 

Examples:
 
DWDObservationSites -> DWDObservationStations
DWDObservationData -> DWDObservationValues
etc.

Working on a pull request!

**Comment by amotl** [comment]
Hi Marvin,

thank you very much!

Wetterdienst itself is very much in flux, so we appreciate that people are taking care. As mentioned at https://github.com/earthobservations/wetterdienst/issues/347#issuecomment-775362204, the best thing to help that both code bases will not diverge too much would be to unify them into the same repository and cover both angles through the same test harness, following the [monorepo](https://en.wikipedia.org/wiki/Monorepo) paradigm.

However, because the contribution by @meteoDaniel just happened a few hours ago, that obviously hasn't happened yet. We are very happy that you are chiming in so quickly and are looking forward to your patch.

With kind regards,
Andreas.

**Comment by meteoDaniel** [comment]
@deepweather are you finished with the refactoring? If you are working on that I would prefer to start with some of the open features to enhance the service. Let me know and thanks for contributing! 

Btw. nice nickname ;)

**Comment by deepweather** [comment]
Hey Andreas, 
got it, thanks for explaining. 

@meteoDaniel 
Nope, unfortunately did not finish yesterday, I'll work on that after end of working day.  Sure, thanks to everybody contributing to earthobservations for the nice tools! 

:+1: Thanks

Best, 
Marvin

**Comment by gutzbenj** [comment]
Hey guys,

actually I'm already working on further changes within the PR at [1]. However everything resulting from this PR will only simplify things in terms of jumping from a stations listing directly to the corresponding values ;) so, anyway, thanks for your effort on this side of the lib.

[1] https://github.com/earthobservations/wetterdienst/pull/345

**Comment by meteoDaniel** [comment]
This PR solves the most recent incompatibilities  https://github.com/earthobservations/wetterdienst-ui/tree/update_wetterdiest_add_docker 
@gutzbenj let me know if there is a new release on your side. I will make further adaptions.

**Comment by gutzbenj** [comment]
> This PR solves the most recent incompatibilities https://github.com/earthobservations/wetterdienst-ui/tree/update_wetterdiest_add_docker
> @gutzbenj let me know if there is a new release on your side. I will make further adaptions.

I'm still working on the new version (rather fixing the tests, docs,...)! Apparently it changes a lot so I'll have to make sure, that everything makes sense after all and has its defined place. After speaking with @amotl we will also do "one last big renaming" in order to give the new structure a more sensible name.

**Comment by meteoDaniel** [comment]
@gutzbenj what are you thinking about for the renaming?

**Comment by gutzbenj** [comment]
The renaming would only be from **DWDObservationStations** to **DWDObservationRequest**. However from this point further renamings won't effect any of the other code, as we'd go from this one class to the station listing, and from that again to the values.
